Repository unicef/hope, pull requests merged in 2024-12, with the labels that each got.

#4473 [AB#223285]-fix payment records not fixed by program
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/apollo/queries/payments/AllPaymentRecordsAndPayments.ts
  src/frontend/src/components/grievances/LookUps/LookUpPaymentRecordTable/LookUpPaymentRecordTable.tsx
  src/frontend/src/containers/tables/payments/PaymentRecordAndPaymentHouseholdTable/PaymentRecordAndPaymentHouseholdTable.tsx
  src/frontend/src/containers/tables/payments/PaymentRecordAndPaymentHouseholdTable/__snapshots__/PaymentRecordAndPaymentHouseholdTable.test.tsx.snap
  src/frontend/src/containers/tables/payments/PaymentRecordAndPaymentPeopleTable/PaymentRecordAndPaymentPeopleTable.tsx
  src/frontend/src/containers/tables/payments/PaymentRecordAndPaymentPeopleTable/__snapshots__/PaymentRecordAndPaymentPeopleTable.test.tsx.snap
Labels: bug, frontend

#4481 [HOTFIX] [223015] Add new Gender values
  pyproject.toml
  src/frontend/data/schema.graphql
  src/frontend/package.json
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/components/payments/CreateVerificationPlan.tsx
  src/frontend/src/components/payments/EditVerificationPlan.tsx
  src/frontend/src/components/people/PeopleFilter.tsx
  src/frontend/src/components/periodicDataUpdates/FilterIndividuals.tsx
  src/frontend/src/components/population/IndividualsFilter.tsx
  src/frontend/src/containers/pages/accountability/communication/CreateCommunicationPage.tsx
  src/frontend/src/containers/pages/accountability/surveys/CreateSurveyPage.tsx
  src/frontend/src/restgenerated/models/SexEnum.ts
  src/frontend/src/utils/utils.ts
  src/hct_mis_api/apps/household/celery_tasks.py
  src/hct_mis_api/apps/household/migrations/0189_migration.py
  src/hct_mis_api/apps/household/models.py
  src/hct_mis_api/apps/payment/migrations/0148_migration.py
  src/hct_mis_api/apps/payment/models.py
  src/hct_mis_api/one_time_scripts/universal_individual_update_script/validator_and_handlers.py
  tests/unit/api/test_push_people.py
  tests/unit/apps/core/snapshots/snap_test_all_fields_attributes_query.py
  tests/unit/apps/core/test_files/kobo-template-invalid.xlsx
  tests/unit/apps/core/test_files/kobo-template-valid.xlsx
  tests/unit/apps/grievance/test_close_data_change_tickets.py
  tests/unit/apps/household/test_individual_xlsx_update.py
  tests/unit/apps/registration_datahub/test_rdi_merge.py
Labels: hotfix, backend

#4497 Unstable tests
  tests/selenium/filters/test_filters.py
  tests/selenium/grievance/grievance_tickets/test_grievance_tickets.py
  tests/selenium/payment_verification/test_payment_verification.py
  tests/selenium/people/test_people.py
  tests/selenium/program_details/test_program_details.py
  tests/selenium/programme_management/test_programme_management.py
Labels: selenium

#4492 [STG] Fix TP Collector filter
  src/hct_mis_api/apps/targeting/models.py
Labels: bug

#4506 [225556] Do not reset permissions on upgrade
  src/hct_mis_api/apps/core/management/commands/generateroles.py
  src/hct_mis_api/apps/core/management/commands/upgrade.py
Labels: backend

#4508 [STG] Payment Plan export xlsx: added FSP template doc types list
  src/hct_mis_api/apps/household/models.py
  src/hct_mis_api/apps/payment/admin.py
  src/hct_mis_api/apps/payment/migrations/0007_migration.py
  src/hct_mis_api/apps/payment/models/payment.py
  src/hct_mis_api/apps/payment/xlsx/xlsx_payment_plan_export_per_fsp_service.py
  src/hct_mis_api/migrations_script/main.py
  tests/unit/apps/payment/test_fsp_xlsx_template_get_column_value.py
Labels: payment module, backend

#4450 E2E stabilization
  .github/helpers/docker-compose.selenium.yml
  .github/workflows/ci.yml
  src/hct_mis_api/apps/payment/api/views.py
  tests/selenium/grievance/grievance_dashboard/test_grievance_dashboard.py
  tests/selenium/managerial_console/test_managerial_console.py
  tests/selenium/payment_verification/test_payment_verification.py
  tests/selenium/programme_population/test_periodic_data_templates.py
  tests/selenium/targeting/test_targeting.py
Labels: selenium

#4520 [HOTFIX]- Fix perm cycles
  src/frontend/src/containers/pages/paymentmodule/ProgramCycle/PaymentPlanDetails/PaymentPlanDetailsHeader.tsx
  src/frontend/src/containers/pages/paymentmodule/ProgramCycle/ProgramCyclePage.tsx
Labels: hotfix

#4526 Fix create Payment Plan: household list when engine formula applied
  src/hct_mis_api/apps/payment/services/payment_plan_services.py
Labels: bug, backend
