Repository unicef/hope, pull requests merged in 2024-11, with the labels that each got.

#4393 [219912] Add all fields to country endpoint, modify tests
  src/hct_mis_api/api/endpoints/serializers.py
  tests/unit/api/test_lookups.py
Labels: backend

#4408 [220866] BankAccountInfo changes
  src/hct_mis_api/apps/household/migrations/0188_migration.py
  src/hct_mis_api/apps/household/models.py
Labels: backend

#4407 [219876] [219849] Apply Mailjet for Send API token; Change payment notification recipients logic
  src/hct_mis_api/api/admin.py
  src/hct_mis_api/apps/payment/notifications.py
  src/hct_mis_api/apps/utils/mailjet.py
  tests/unit/api/test_api_token.py
  tests/unit/apps/payment/test_payment_notification.py
Labels: backend

#4416 [221081] Geo API - add filters
  src/hct_mis_api/api/filters.py
  tests/unit/api/test_lookups.py
Labels: backend

#4417 [201639]-add Delivery Mechanism section for people
  src/frontend/src/containers/pages/people/PeopleDetailsPage.tsx
Labels: frontend

#4428 Add mailjet exception logging
  src/hct_mis_api/apps/utils/celery_tasks.py
  src/hct_mis_api/apps/utils/mailjet.py
  tests/unit/api/test_api_token.py
  tests/unit/apps/household/test_individual_iban_xlsx_update.py
  tests/unit/apps/payment/test_finish_verification_plan.py
  tests/unit/apps/payment/test_payment_notification.py
  tests/unit/apps/reporting/test_generate_dashboard_report_service.py
  tests/unit/apps/sanction_list/test_check_against_sanction_list_task.py
  tests/unit/apps/utils/test_mailjet.py
Labels: backend

#4330 New dashboard
  development_tools/local_selenium_init.sh
  pdm.lock
  src/frontend/src/containers/pages/dashboard/NewDashboardPage.tsx
  src/frontend/src/containers/routers/AllProgramsRoutesSwitch.tsx
  src/frontend/src/containers/routers/SelectedProgramRoutesSwitch.tsx
  src/frontend/vite.config.ts
  src/hct_mis_api/api/urls.py
  src/hct_mis_api/apps/core/tasks_schedules.py
  src/hct_mis_api/apps/dashboard/__init__.py
  src/hct_mis_api/apps/dashboard/admin.py
  src/hct_mis_api/apps/dashboard/apps.py
  src/hct_mis_api/apps/dashboard/celery_tasks.py
  src/hct_mis_api/apps/dashboard/management/commands/save_dashboard_data.py
  src/hct_mis_api/apps/dashboard/serializers.py
  src/hct_mis_api/apps/dashboard/services.py
  src/hct_mis_api/apps/dashboard/static/dashboard/css/Humanitarian-Icons.css
  src/hct_mis_api/apps/dashboard/static/dashboard/css/dashboard.css
  src/hct_mis_api/apps/dashboard/static/dashboard/css/dc.min.css
  src/hct_mis_api/apps/dashboard/static/dashboard/css/tailwind.min.css
  src/hct_mis_api/apps/dashboard/static/dashboard/fonts/Humanitarian-Icons.ttf
  src/hct_mis_api/apps/dashboard/static/dashboard/js/crossfilter.min.js
  src/hct_mis_api/apps/dashboard/static/dashboard/js/d3-scale-chromatic.v1.min.js
  src/hct_mis_api/apps/dashboard/static/dashboard/js/d3.min.js
  src/hct_mis_api/apps/dashboard/static/dashboard/js/dc.min.js
  src/hct_mis_api/apps/dashboard/static/dashboard/js/dc.min.js.map
  src/hct_mis_api/apps/dashboard/templates/dashboard/dashboard.html
  src/hct_mis_api/apps/dashboard/urls.py
  src/hct_mis_api/apps/dashboard/views.py
  src/hct_mis_api/config/settings.py
  src/hct_mis_api/middlewares/xframe.py
  tests/selenium/conftest.py
  tests/selenium/country_dashboard/test_country_dashboard.py
  tests/selenium/page_object/country_dashboard/country_dashboard.py
  tests/unit/apps/dashboard/__init__.py
  tests/unit/apps/dashboard/test_services.py
  tests/unit/apps/dashboard/test_tasks.py
  tests/unit/apps/dashboard/test_views.py
  tests/unit/conftest.py
  tests/unit/fixtures/__init__.py
  tests/unit/fixtures/common.py
  tests/unit/fixtures/dashboard.py
Labels: backend, frontend

#4429 Emails - fix type DEFAULT_EMAIL_DISPLAY
  src/hct_mis_api/config/env.py
Labels: backend

#4431 [222138] Emails - fix type for DEFAULT_EMAIL_DISPLAY
  src/hct_mis_api/config/env.py
Labels: backend

#4411 Selenium: Update Instruction
  tests/selenium/README.md
Labels: selenium

#4434 Fix test_payment_plan_happy_path
  tests/selenium/page_object/payment_module/payment_module_details.py
  tests/selenium/payment_module/test_payment_plans.py
Labels: selenium

#4441 [#AB221685]-fix status label width payment plan details page
  src/frontend/src/components/paymentmodule/EditPaymentPlan/EditPaymentPlanHeader/EditPaymentPlanHeader.tsx
  src/frontend/src/components/paymentmodule/EditPaymentPlan/EditPaymentPlanHeader/__snapshots__/EditPaymentPlanHeader.test.tsx.snap
  src/frontend/src/components/paymentmodule/FollowUpPaymentPlanDetails/FollowUpPaymentPlanDetailsHeader/FollowUpPaymentPlanDetailsHeader.tsx
  src/frontend/src/components/paymentmodulepeople/EditPaymentPlan/EditPaymentPlanHeader/EditPaymentPlanHeader.tsx
  src/frontend/src/components/paymentmodulepeople/EditPaymentPlan/EditPaymentPlanHeader/__snapshots__/EditPaymentPlanHeader.test.tsx.snap
  src/frontend/src/components/paymentmodulepeople/FollowUpPaymentPlanDetails/FollowUpPaymentPlanDetailsHeader/FollowUpPaymentPlanDetailsHeader.tsx
  src/frontend/src/containers/pages/headers/TargetPopulationPageHeader.tsx
  src/frontend/src/containers/pages/paymentmodule/ProgramCycle/PaymentPlanDetails/PaymentPlanDetailsHeader.tsx
Labels: bug, frontend

#4443 223047_Data_of_mobile_wallet_provider_not_imported_for_all_records_o…
  pyproject.toml
  src/frontend/package.json
  src/hct_mis_api/apps/registration_datahub/tasks/rdi_kobo_create.py
  tests/unit/apps/registration_datahub/test_file/kobo_submissions.json
  tests/unit/apps/registration_datahub/test_rdi_kobo_create.py
Labels: hotfix

#4421 [221446] Script to add PDU fields
  src/hct_mis_api/one_time_scripts/add_pdu_fields.py
  tests/unit/one_time_scripts/test_add_pdu_fields.py
Labels: backend

#4447 Fix TestAddPDUFields after merge
  tests/unit/one_time_scripts/test_add_pdu_fields.py
Labels: backend

#4453 Use admin area name instead of pcode in export of payments
  pyproject.toml
  src/frontend/package.json
  src/hct_mis_api/apps/payment/models.py
  tests/unit/apps/payment/test_models.py
Labels: hotfix

#4288 E2E speed improvement
  .github/workflows/ci.yml
  development_tools/compose.yml
  development_tools/local_selenium_init.sh
  src/frontend/src/components/grievances/GrievancesSidebar/GrievancesSidebar.tsx
  src/frontend/src/components/grievances/LookUps/LookUpReassignRole/LookUpReassignRole.tsx
  src/frontend/src/components/grievances/NeedsAdjudication/NeedsAdjudicationTable.tsx
  src/frontend/src/components/grievances/ReassignMultipleRoleBox.tsx
  src/frontend/src/components/grievances/ReassignRoleBox.tsx
  src/frontend/src/containers/GlobalProgramSelect.tsx
  src/hct_mis_api/apps/account/fixtures.py
  src/hct_mis_api/apps/geo/fixtures/data_small.json
  src/hct_mis_api/apps/grievance/fixtures/data-cypress.json
  src/hct_mis_api/apps/grievance/mutations.py
  src/hct_mis_api/apps/grievance/services/data_change/utils.py
  src/hct_mis_api/apps/grievance/services/needs_adjudication_ticket_services.py
  src/hct_mis_api/apps/grievance/services/reassign_roles_services.py
  src/hct_mis_api/apps/household/fixtures/data-cypress.json
  tests/selenium/accountability/test_communication.py
  tests/selenium/accountability/test_surveys.py
  tests/selenium/conftest.py
  tests/selenium/country_dashboard/test_country_dashboard.py
  tests/selenium/drawer/test_drawer.py
  tests/selenium/filters/test_filters.py
  tests/selenium/grievance/feedback/test_feedback.py
  tests/selenium/grievance/grievance_dashboard/test_grievance_dashboard.py
  tests/selenium/grievance/grievance_tickets/test_grievance_tickets.py
  tests/selenium/helpers/helper.py
  tests/selenium/helpers/rdi_import_50_hh_50_ind.xlsx
  tests/selenium/login_via_admin_panel/test_login.py
  tests/selenium/managerial_console/test_managerial_console.py
  tests/selenium/page_object/base_components.py
  tests/selenium/page_object/country_dashboard/country_dashboard.py
  tests/selenium/page_object/grievance/details_grievance_page.py
  tests/selenium/page_object/grievance/grievance_tickets.py
  tests/selenium/page_object/grievance/new_feedback.py
  tests/selenium/page_object/payment_verification/payment_record.py
  tests/selenium/page_object/programme_details/programme_details.py
  tests/selenium/page_object/programme_management/programme_management.py
  tests/selenium/page_object/targeting/targeting.py
  tests/selenium/payment_module/test_payment_plans.py
  tests/selenium/payment_module/test_program_cycles.py
  tests/selenium/payment_verification/test_payment_verification.py
  tests/selenium/people/test_people.py
  tests/selenium/people/test_people_periodic_data_update.py
  tests/selenium/program_details/test_program_details.py
  tests/selenium/program_log/test_program_log.py
  tests/selenium/programme_management/test_programme_management.py
  tests/selenium/programme_population/test_households.py
  tests/selenium/programme_population/test_individuals.py
  tests/selenium/programme_population/test_periodic_data_templates.py
  tests/selenium/programme_population/test_periodic_data_update_upload.py
  tests/selenium/programme_user/test_programme_user.py
  tests/selenium/registration_data_import/test_registration_data_import.py
  tests/selenium/targeting/test_targeting.py
  tests/unit/apps/grievance/test_adjudication_ticket_partner_permission.py
  tests/unit/apps/grievance/test_reassign_roles_services.py
  tests/unit/apps/grievance/test_services_utils.py
  tests/unit/apps/payment/test_payment_plan_views.py
Labels: enhancement, selenium

#4478 [HOTFIX] allAreasTree query filter by max area_level 3
  src/hct_mis_api/apps/geo/fixtures/data.json
  src/hct_mis_api/apps/geo/schema.py
  src/hct_mis_api/apps/program/admin.py
  tests/unit/apps/core/snapshots/snap_test_all_fields_attributes_query.py
  tests/unit/apps/geo/snapshots/snap_test_schema.py
  tests/unit/apps/geo/test_schema.py
Labels: hotfix

#4477 TP fix filtering if answer is NO
  development_tools/local_selenium_init.sh
  src/hct_mis_api/apps/targeting/models.py
  tests/selenium/conftest.py
  tests/unit/apps/targeting/snapshots/snap_test_copy_target_population_mutation.py
  tests/unit/apps/targeting/snapshots/snap_test_create_target_population_mutation.py
  tests/unit/apps/targeting/test_copy_target_population_mutation.py
  tests/unit/apps/targeting/test_create_target_population_mutation.py
  tests/unit/apps/targeting/test_individual_block_filters.py
  tests/unit/apps/targeting/test_targeting_criteria_rule_filter.py
Labels: backend, frontend
