Repository unicef/hope, pull requests merged in 2025-01, with the labels that each got.

#4543 Hotfix New currency
  src/hct_mis_api/apps/core/currencies.py
  src/hct_mis_api/apps/household/migrations/0006_migration.py
  src/hct_mis_api/apps/payment/migrations/0008_migration.py
  tests/unit/apps/core/snapshots/snap_test_all_fields_attributes_query.py
  tests/unit/apps/core/test_files/kobo-template-invalid.xlsx
  tests/unit/apps/core/test_files/kobo-template-valid.xlsx
Labels: hotfix

#4553 DEV update migration script TP>PP
  src/hct_mis_api/one_time_scripts/migrate_tp_into_pp.py
  tests/unit/one_time_scripts/test_migrate_tp_into_pp.py
Labels: backend, work in progress

#4513 RDI Program Population filter by ids
  src/frontend/data/schema.graphql
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/apollo/mutations/rdi/CreateRegistrationProgramPopulationImport.ts
  src/frontend/src/components/rdi/create/RegistrationDataImportCreateDialog.tsx
  src/frontend/src/components/rdi/create/programPopulation/CreateImportFromProgramPopulation.tsx
  src/frontend/src/shared/Formik/FormikRadioGroup/FormikRadioGroup.tsx
  src/hct_mis_api/apps/registration_data/migrations/0002_migration.py
  src/hct_mis_api/apps/registration_data/models.py
  src/hct_mis_api/apps/registration_datahub/inputs.py
  src/hct_mis_api/apps/registration_datahub/mutations.py
  src/hct_mis_api/apps/registration_datahub/tasks/import_program_population.py
  src/hct_mis_api/apps/registration_datahub/utils.py
  src/hct_mis_api/migrations_script/main.py
  tests/unit/apps/registration_datahub/snapshots/snap_test_registration_data_import_program_population_mutation.py
  tests/unit/apps/registration_datahub/test_registration_data_import_program_population_mutation.py
Labels: backend, frontend

#4556 Fix Grievance validate flex fields value with date type
  src/hct_mis_api/apps/grievance/services/data_change/utils.py
  tests/unit/apps/grievance/test_services_utils.py
Labels: backend

#4552 Fix grievance ticket details page for System Flagging ticket
  src/frontend/src/components/grievances/GrievancesSidebar/GrievancesSidebar.tsx
Labels: hotfix

#4547 South sudan update script fix
  src/hct_mis_api/one_time_scripts/south_sudan_update_script.py
  src/hct_mis_api/one_time_scripts/universal_individual_update_script/universal_individual_update_script.py
  tests/unit/one_time_scripts/files/update_script_sudan.xlsx
  tests/unit/one_time_scripts/test_south_sudan_update_script.py
Labels: hotfix

#4565 adjust local env layout variable
  src/frontend/src/components/core/Drawer/Drawer.tsx
Labels: enhancement, frontend

#4584 STG Fix grievance upd ind
  src/hct_mis_api/apps/grievance/services/data_change/utils.py
  tests/unit/apps/grievance/test_services_utils.py
Labels: bug, backend

#4582 add beneficiary group required attribute in Program Form
  src/frontend/data/schema.graphql
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/apollo/queries/core/DataCollectionTypeChoiceData.ts
  src/frontend/src/components/core/Drawer/Drawer.tsx
  src/frontend/src/containers/forms/ProgramForm.tsx
  src/hct_mis_api/apps/core/schema.py
  src/hct_mis_api/apps/grievance/migrations/0005_migration.py
  tests/unit/apps/core/snapshots/snap_test_schema.py
  tests/unit/apps/core/test_schema.py
Labels: bug, frontend

#4588 fix biometric golden record results
  src/frontend/src/containers/tables/rdi/ImportedIndividualsTable/ImportedIndividualsTableRow.tsx
  src/frontend/src/containers/tables/rdi/ImportedPeopleTable/ImportedPeopleTableRow.tsx
Labels: bug, frontend

#4593 Update script to accomodate phone number in south sudan upate script
  src/hct_mis_api/one_time_scripts/south_sudan_update_script.py
  tests/unit/one_time_scripts/files/update_script_sudan.xlsx
  tests/unit/one_time_scripts/test_south_sudan_update_script.py
Labels: hotfix

#4577 STG update migration script TP>PP
  src/frontend/data/schema.graphql
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/containers/pages/headers/TargetPopulationPageHeader.tsx
  src/hct_mis_api/apps/payment/migrations/0009_migration.py
  src/hct_mis_api/apps/payment/migrations/0013_migration.py
  src/hct_mis_api/apps/payment/models/payment.py
  src/hct_mis_api/one_time_scripts/migrate_tp_into_pp.py
  tests/unit/apps/payment/snapshots/snap_test_all_payment_plan_queries.py
  tests/unit/one_time_scripts/test_migrate_tp_into_pp.py
Labels: backend

#4600 Hotfix step 2 atomic block
  src/hct_mis_api/one_time_scripts/migrate_tp_into_pp.py
Labels: hotfix

#4603 HotFix Script step 2 argument with BA list
  src/hct_mis_api/one_time_scripts/migrate_tp_into_pp.py
Labels: hotfix
