Repository unicef/hope, pull requests merged in 2025-04, with the labels that each got.

#4725 Fix dashboard grouping
  pyproject.toml
  src/frontend/package.json
  src/hct_mis_api/apps/dashboard/services.py
  src/hct_mis_api/apps/dashboard/templates/dashboard/global_dashboard.html
  src/hct_mis_api/apps/dashboard/views.py
  tests/unit/apps/dashboard/test_services.py
  tests/unit/fixtures/dashboard.py
  uv.lock
Labels: hotfix, backend

#4731 Bugs 1.04.25
  src/frontend/src/components/grievances/CreateGrievance/Description/Description.tsx
  src/frontend/src/components/grievances/CreateGrievance/Selection/Selection.tsx
  src/frontend/src/components/grievances/Documentation/DocumentationField.tsx
  src/frontend/src/components/grievances/Documentation/NewDocumentationFieldArray.tsx
  src/frontend/src/components/grievances/EditIndividualDataChange/EditIndividualDataChange.tsx
  src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
  src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChangeFieldRow.tsx
  src/frontend/src/components/grievances/GrievancesDetails/GrievancesDetails.tsx
  src/frontend/src/components/grievances/GrievancesDetails/__snapshots__/GrievancesDetails.test.tsx.snap
  src/frontend/src/components/grievances/Notes/Notes.tsx
  src/frontend/src/components/grievances/utils/validateGrievance.ts
  src/frontend/src/containers/pages/grievances/EditGrievancePage.tsx
  src/frontend/src/containers/tables/targeting/TargetPopulationPeopleTable/TargetPopulationPeopleRow.tsx
  src/frontend/src/utils/en.json
  tests/selenium/page_object/grievance/details_grievance_page.py
Labels: bug, frontend, staging

#4729 WIP // REST TP/PP CRUD
  src/hct_mis_api/api/urls.py
  src/hct_mis_api/apps/core/rest_api.py
  src/hct_mis_api/apps/payment/api/serializers.py
  src/hct_mis_api/apps/payment/api/views.py
  src/hct_mis_api/apps/payment/mutations.py
  src/hct_mis_api/apps/payment/services/payment_plan_services.py
  src/hct_mis_api/apps/steficon/api/serializers.py
  src/hct_mis_api/apps/steficon/views.py
  src/hct_mis_api/apps/targeting/api/serializers.py
  src/hct_mis_api/apps/targeting/validators.py
  src/hct_mis_api/apps/utils/exceptions.py
  tests/unit/apps/payment/snapshots/snap_test_action_payment_plan_mutation.py
  tests/unit/apps/payment/snapshots/snap_test_split_payment_plan_mutation.py
  tests/unit/apps/payment/test_payment_plan_mutation.py
  tests/unit/apps/payment/test_payment_plan_reconciliation.py
  tests/unit/apps/payment/test_payment_plan_services.py
  tests/unit/apps/payment/test_payment_plan_views.py
  tests/unit/apps/payment/test_payment_signature.py
  tests/unit/apps/payment/test_serializers.py
  tests/unit/apps/targeting/snapshots/__init__.py
  tests/unit/apps/targeting/snapshots/snap_test_candidate_households_by_targeting_criteria_query.py
  tests/unit/apps/targeting/snapshots/snap_test_copy_target_population_mutation.py
  tests/unit/apps/targeting/snapshots/snap_test_final_households_by_targeting_criteria_query.py
  tests/unit/apps/targeting/test_copy_target_population_mutation.py
  tests/unit/apps/targeting/test_targeting_serializers.py
  tests/unit/apps/targeting/test_targeting_validators.py
Labels: work in progress

#4749 WIP // Rest Payment Verification
  src/hct_mis_api/apps/payment/api/caches.py
  src/hct_mis_api/apps/payment/api/serializers.py
  src/hct_mis_api/apps/payment/api/urls.py
  src/hct_mis_api/apps/payment/api/views.py
Labels: work in progress

#4771 nigeria hotfix
  pyproject.toml
  src/frontend/package.json
  src/hct_mis_api/contrib/aurora/services/generic_registration_service.py
  src/hct_mis_api/contrib/aurora/services/nigeria_people_registration_service.py
  tests/unit/apps/registration_datahub/test_nigeria_people_registration_service.py
Labels: hotfix

#4782 funds commitment display in accepted state
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/apollo/queries/paymentmodule/PaymentPlan.ts
  src/frontend/src/components/paymentmodule/PaymentPlanDetails/FundsCommitment/FundsCommitmentSection.tsx
  src/frontend/src/containers/pages/paymentmodule/FollowUpPaymentPlanDetailsPage.tsx
  src/frontend/src/containers/pages/paymentmodule/ProgramCycle/PaymentPlanDetails/PaymentPlanDetailsPage.tsx
  src/frontend/src/containers/pages/paymentmodulepeople/PeoplePaymentPlanDetailsPage.tsx
  src/hct_mis_api/apps/payment/admin.py
  src/hct_mis_api/contrib/vision/admin.py
  src/hct_mis_api/contrib/vision/models.py
Labels: frontend
