Repository unicef/hope, pull requests merged in 2025-03, with the labels that each got.

#4655 Fix e2e Create TP
  pyproject.toml
  src/frontend/package.json
  tests/selenium/targeting/test_targeting.py
Labels: hotfix

#4665 🔥hotfix-fix permission HH/People details section Payments Table
  pyproject.toml
  src/frontend/package.json
  src/frontend/src/containers/pages/people/PeopleDetailsPage.tsx
  src/frontend/src/containers/pages/population/PopulationHouseholdDetailsPage.tsx
Labels: hotfix, frontend

#4675 STG // Fix create PaymentVerificationSummary after PG sync
  src/hct_mis_api/apps/payment/services/payment_gateway.py
  tests/unit/apps/payment/test_payment_gateway_service.py
Labels: backend

#4671 Update django form
  src/hct_mis_api/api/admin.py
  src/hct_mis_api/apps/account/admin/ad.py
  src/hct_mis_api/apps/account/templates/admin/load_users.html
  src/hct_mis_api/apps/household/admin/household.py
  src/hct_mis_api/apps/household/forms.py
  src/hct_mis_api/apps/household/templates/admin/household/household/withdraw_households_from_list.html
  src/hct_mis_api/apps/steficon/admin.py
  tests/unit/apps/household/test_household_admin.py
  tests/unit/apps/steficon/test_admin.py
Labels: backend

#4688 add optional chaining if no individual data (delivery mechanism)
  src/frontend/src/components/population/IndividualDeliveryMechanisms.tsx
Labels: bug

#4695 [AB#238960]-fix slider field not displaying
  src/frontend/src/shared/Formik/FormikSliderField/FormikSliderField.tsx
Labels: bug

#4708 Dashboard Hotfix
  pyproject.toml
  src/frontend/package.json
  src/hct_mis_api/apps/dashboard/services.py
  tests/selenium/conftest.py
  tests/unit/apps/dashboard/test_services.py
  tests/unit/fixtures/dashboard.py
Labels: hotfix, backend
