Repository unicef/hope, pull requests merged in 2025-07, with the labels that each got.

#4929 Payment Verification Rename labels
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/apollo/queries/paymentmodule/AllPaymentPlansForTable.ts
  src/frontend/src/components/payments/CashPlanDetailsSection.tsx
  src/frontend/src/containers/tables/payments/PaymentVerificationTable/PaymentVerificationHeadCells.tsx
  src/frontend/src/containers/tables/payments/PaymentVerificationTable/PaymentVerificationTableRow.tsx
  src/frontend/src/containers/tables/payments/PaymentVerificationTable/__snapshots__/PaymentVerificationTable.test.tsx.snap
  tests/selenium/page_object/payment_verification/payment_verification.py
  tests/selenium/payment_verification/test_payment_verification.py
Labels: frontend

#4943 Bug 244721: Grievances - Unable to close NA ticket
  src/hct_mis_api/apps/household/models.py
  tests/unit/apps/household/test_models.py
  tests/unit/apps/registration_datahub/snapshots/snap_test_imported_household_query.py
  tests/unit/apps/registration_datahub/test_imported_household_query.py
Labels: enhancement

#5006 Hotfix fix exchange rate history
  src/hct_mis_api/apps/core/exchange_rates/api.py
  tests/unit/apps/core/test_exchange_rates.py
Labels: hotfix
