Repository unicef/hope, pull requests merged in 2025-02, with the labels that each got.

#4617 🔥hotfix-[AB#234220]-add edit payment channel to people data change
  pyproject.toml
  src/frontend/package.json
  src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
Labels: hotfix, frontend

#4618 [AB#233871]-add description to documents, documentation labels
  src/frontend/src/components/grievances/CreateGrievance/Description/Description.tsx
  src/frontend/src/components/grievances/EditIndividualDataChange/EditIndividualDataChange.tsx
  src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
  src/frontend/src/containers/pages/grievances/EditGrievancePage.tsx
  src/frontend/src/utils/en.json
Labels: frontend

#4624 Aurora cache fixes
  src/hct_mis_api/contrib/aurora/apps.py
  src/hct_mis_api/contrib/aurora/caches.py
  src/hct_mis_api/contrib/aurora/signals.py
  src/hct_mis_api/contrib/aurora/views.py
  tests/unit/api/test_aurora_api.py
Labels: backend

#4633 Grievance LookUp Individual Table add `withdrawn: false` filter
  src/frontend/src/components/grievances/LookUps/LookUpIndividualTable/LookUpIndividualTable.tsx
Labels: bug

#4637 [AB#224937]-loading button program
  src/frontend/src/components/programs/CreateProgram/PartnersStep.tsx
  src/frontend/src/components/programs/EditProgram/PartnersStep.tsx
  src/frontend/src/containers/pages/program/CreateProgramPage.tsx
  src/frontend/src/containers/pages/program/DuplicateProgramPage.tsx
  src/frontend/src/containers/pages/program/EditProgramPage.tsx
Labels: frontend

#4641 STG Fix population default filters [Rdi merge status]
  src/frontend/src/components/grievances/LookUps/LookUpIndividualTable/LookUpIndividualTable.tsx
  src/frontend/src/containers/tables/people/PeopleListTable/PeopleListTable.tsx
Labels: bug

#4643 fix filters layout
  src/frontend/data/schema.graphql
  src/frontend/src/__generated__/graphql.tsx
  src/frontend/src/components/paymentmodule/CreatePaymentPlan/PaymentPlanParameters/PaymentPlanParameters.tsx
  src/frontend/src/containers/pages/paymentmodule/ProgramCycle/ProgramCycleDetails/PaymentPlansFilters.tsx
  src/frontend/src/containers/tables/ProgramCyclesTablePaymentModule/ProgramCyclesFilters.tsx
Labels: bug

#4654 🔥hotfix -[AB#237370]- Old TPs not appearing in the targeting module for all Social Workers Programme
  pyproject.toml
  src/frontend/package.json
  src/frontend/src/containers/tables/targeting/TargetPopulationForPeopleTable/TargetPopulationForPeopleTable.tsx
Labels: bug, hotfix, frontend

#4659 Hotfix 237470 Admin load AD users
  pyproject.toml
  src/frontend/package.json
  src/hct_mis_api/apps/account/admin/ad.py
Labels: bug, hotfix, backend

#4657 Fix tp status mapping
  src/frontend/src/containers/tables/targeting/TargetPopulationForPeopleTable/TargetPopulationForPeopleTableRow.tsx
  src/frontend/src/utils/utils.ts
Labels: bug, frontend

#4647 Upd Export PaymentPlan XLSX with auth code
  src/hct_mis_api/apps/payment/models/payment.py
  src/hct_mis_api/apps/payment/schema.py
  tests/unit/apps/payment/snapshots/snap_test_all_payment_plan_queries.py
Labels: backend
